{{- if .Values.offerings.content }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigfleet-oracle-cloud.fullname" . }}-offerings
  labels:
    {{- include "bigfleet-oracle-cloud.labels" . | nindent 4 }}
data:
  offerings.json: |
    {{- .Values.offerings.content | nindent 4 }}
{{- end }}
{{- if .Values.baseUserData.content }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigfleet-oracle-cloud.fullname" . }}-base-user-data
  labels:
    {{- include "bigfleet-oracle-cloud.labels" . | nindent 4 }}
data:
  base-user-data: |
    {{- .Values.baseUserData.content | nindent 4 }}
{{- end }}
{{- if .Values.prices.content }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigfleet-oracle-cloud.fullname" . }}-prices
  labels:
    {{- include "bigfleet-oracle-cloud.labels" . | nindent 4 }}
data:
  prices.yaml: |
    {{- .Values.prices.content | nindent 4 }}
{{- end }}
