apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigfleet-hetzner.fullname" . }}
  labels:
    {{- include "bigfleet-hetzner.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.metrics.prometheusScrape }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.ports.metrics | quote }}
    prometheus.io/path: "/metrics"
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "bigfleet-hetzner.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      appProtocol: grpc
    - name: metrics
      port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
