{{- if .Values.offerings.content }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigfleet-azure.fullname" . }}-offerings
  labels:
    {{- include "bigfleet-azure.labels" . | nindent 4 }}
data:
  offerings.json: |
    {{- .Values.offerings.content | nindent 4 }}
{{- end }}
{{- if .Values.baseUserData.content }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigfleet-azure.fullname" . }}-base-user-data
  labels:
    {{- include "bigfleet-azure.labels" . | nindent 4 }}
data:
  base-user-data: |
    {{- .Values.baseUserData.content | nindent 4 }}
{{- end }}
{{- if .Values.azure.sshPublicKey }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigfleet-azure.fullname" . }}-ssh
  labels:
    {{- include "bigfleet-azure.labels" . | nindent 4 }}
data:
  ssh.pub: |
    {{- .Values.azure.sshPublicKey | nindent 4 }}
{{- end }}
